#!/bin/bash

# Improved image download script for Arc Raiders Wiki
# Uses curl with proper headers and follows redirects

OUTPUT_DIR="../assets/images/items"
mkdir -p "$OUTPUT_DIR"

# Array of all item images from the wiki
declare -a ITEMS=(
  "advanced_arc_powercell|https://static.wikia.nocookie.net/arc-raiders/images/3/31/Advanced_ARC_Powercell.png"
  "advanced_electrical_components|https://static.wikia.nocookie.net/arc-raiders/images/9/9b/Advanced_Electrical_Components.png"
  "advanced_mechanical_components|https://static.wikia.nocookie.net/arc-raiders/images/2/25/Advanced_Mechanical_Components.png"
  "agave|https://static.wikia.nocookie.net/arc-raiders/images/4/47/Agave.png"
  "agave_juice|https://static.wikia.nocookie.net/arc-raiders/images/a/a8/Agave_Juice.png"
  "air_freshener|https://static.wikia.nocookie.net/arc-raiders/images/0/03/Air_Freshener.png"
  "alarm_clock|https://static.wikia.nocookie.net/arc-raiders/images/9/95/Alarm_Clock.png"
  "ammunition_crate_common|https://static.wikia.nocookie.net/arc-raiders/images/6/6e/Ammunition_Crate_%28Common%29.png"
  "ammunition_crate_uncommon|https://static.wikia.nocookie.net/arc-raiders/images/8/80/Ammunition_Crate_%28Uncommon%29.png"
  "ammunition_crate_rare|https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Ammunition_Crate_%28Rare%29.png"
  "apricot|https://static.wikia.nocookie.net/arc-raiders/images/1/19/Apricot.png"
  "arc_battery_cell|https://static.wikia.nocookie.net/arc-raiders/images/5/53/ARC_Battery_Cell.png"
  "arc_calibration_kit|https://static.wikia.nocookie.net/arc-raiders/images/b/b5/ARC_Calibration_Kit.png"
  "arc_glass_shard|https://static.wikia.nocookie.net/arc-raiders/images/9/93/ARC_Glass_Shard.png"
  "arc_reinforced_plate|https://static.wikia.nocookie.net/arc-raiders/images/e/e9/ARC_Reinforced_Plate.png"
  "arc_rubber|https://static.wikia.nocookie.net/arc-raiders/images/c/c3/ARC_Rubber.png"
  "basic_electrical_components|https://static.wikia.nocookie.net/arc-raiders/images/a/af/Basic_Electrical_Components.png"
  "basic_mechanical_components|https://static.wikia.nocookie.net/arc-raiders/images/d/d3/Basic_Mechanical_Components.png"
  "batteries|https://static.wikia.nocookie.net/arc-raiders/images/a/a9/Batteries.png"
  "bear_trap|https://static.wikia.nocookie.net/arc-raiders/images/6/6c/Bear_Trap.png"
  "beeswax|https://static.wikia.nocookie.net/arc-raiders/images/b/bb/Beeswax.png"
  "binoculars|https://static.wikia.nocookie.net/arc-raiders/images/1/17/Binoculars.png"
  "blueberries|https://static.wikia.nocookie.net/arc-raiders/images/4/4b/Blueberries.png"
  "bone_saw|https://static.wikia.nocookie.net/arc-raiders/images/c/cd/Bone_Saw.png"
  "bottle_cap|https://static.wikia.nocookie.net/arc-raiders/images/7/7a/Bottle_Cap.png"
  "broken_guitar|https://static.wikia.nocookie.net/arc-raiders/images/5/5f/Broken_Guitar.png"
  "broken_wristwatch|https://static.wikia.nocookie.net/arc-raiders/images/1/12/Broken_Wristwatch.png"
  "canned_food|https://static.wikia.nocookie.net/arc-raiders/images/0/0b/Canned_Food.png"
  "car_battery|https://static.wikia.nocookie.net/arc-raiders/images/6/64/Car_Battery.png"
  "cardboard|https://static.wikia.nocookie.net/arc-raiders/images/e/ee/Cardboard.png"
  "cat_bed|https://static.wikia.nocookie.net/arc-raiders/images/b/b9/Cat_Bed.png"
  "chalk|https://static.wikia.nocookie.net/arc-raiders/images/4/4e/Chalk.png"
  "chemicals|https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Chemicals.png"
  "circuit_board|https://static.wikia.nocookie.net/arc-raiders/images/6/6e/Circuit_Board.png"
  "clean_water|https://static.wikia.nocookie.net/arc-raiders/images/0/0a/Clean_Water.png"
  "coil|https://static.wikia.nocookie.net/arc-raiders/images/b/b9/Coil.png"
  "colander|https://static.wikia.nocookie.net/arc-raiders/images/d/d9/Colander.png"
  "compass|https://static.wikia.nocookie.net/arc-raiders/images/e/e5/Compass.png"
  "computer_mouse|https://static.wikia.nocookie.net/arc-raiders/images/a/a9/Computer_Mouse.png"
  "cooking_pot|https://static.wikia.nocookie.net/arc-raiders/images/c/ca/Cooking_Pot.png"
  "copper_wire|https://static.wikia.nocookie.net/arc-raiders/images/4/4a/Copper_Wire.png"
  "corroded_battery|https://static.wikia.nocookie.net/arc-raiders/images/5/5f/Corroded_Battery.png"
  "cracked_screen|https://static.wikia.nocookie.net/arc-raiders/images/7/72/Cracked_Screen.png"
  "crude_pipe_bomb|https://static.wikia.nocookie.net/arc-raiders/images/7/7e/Crude_Pipe_Bomb.png"
  "cutting_board|https://static.wikia.nocookie.net/arc-raiders/images/4/4f/Cutting_Board.png"
  "damaged_arc_circuitry|https://static.wikia.nocookie.net/arc-raiders/images/d/d5/Damaged_ARC_Circuitry.png"
  "damaged_arc_optics|https://static.wikia.nocookie.net/arc-raiders/images/6/60/Damaged_ARC_Optics.png"
  "damaged_arc_plating|https://static.wikia.nocookie.net/arc-raiders/images/0/07/Damaged_ARC_Plating.png"
  "damaged_tick_pod|https://static.wikia.nocookie.net/arc-raiders/images/d/d6/Damaged_Tick_Pod.png"
  "damaged_wasp_driver|https://static.wikia.nocookie.net/arc-raiders/images/e/e6/Damaged_Wasp_Driver.png"
  "dart_board|https://static.wikia.nocookie.net/arc-raiders/images/4/4d/Dart_Board.png"
  "deflated_football|https://static.wikia.nocookie.net/arc-raiders/images/7/7c/Deflated_Football.png"
  "degraded_arc_rubber|https://static.wikia.nocookie.net/arc-raiders/images/3/37/Degraded_ARC_Rubber.png"
  "diving_goggles|https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Diving_Goggles.png"
  "dog_collar|https://static.wikia.nocookie.net/arc-raiders/images/c/c5/Dog_Collar.png"
  "dried_out_arc_resin|https://static.wikia.nocookie.net/arc-raiders/images/4/4a/Dried_Out_ARC_Resin.png"
  "duct_tape|https://static.wikia.nocookie.net/arc-raiders/images/4/44/Duct_Tape.png"
  "electrical_components|https://static.wikia.nocookie.net/arc-raiders/images/4/4d/Electrical_Components.png"
  "electronics|https://static.wikia.nocookie.net/arc-raiders/images/5/5a/Electronics.png"
  "empty_soda_can|https://static.wikia.nocookie.net/arc-raiders/images/8/88/Empty_Soda_Can.png"
  "energy_drink|https://static.wikia.nocookie.net/arc-raiders/images/4/4e/Energy_Drink.png"
  "fabric|https://static.wikia.nocookie.net/arc-raiders/images/9/95/Fabric.png"
  "figs|https://static.wikia.nocookie.net/arc-raiders/images/e/ec/Figs.png"
  "fire_extinguisher|https://static.wikia.nocookie.net/arc-raiders/images/7/7b/Fire_Extinguisher.png"
  "first_aid_kit|https://static.wikia.nocookie.net/arc-raiders/images/1/16/First_Aid_Kit.png"
  "fishing_line|https://static.wikia.nocookie.net/arc-raiders/images/a/a9/Fishing_Line.png"
  "flashlight|https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Flashlight.png"
  "flask|https://static.wikia.nocookie.net/arc-raiders/images/c/c7/Flask.png"
  "flint|https://static.wikia.nocookie.net/arc-raiders/images/0/0e/Flint.png"
  "flour|https://static.wikia.nocookie.net/arc-raiders/images/a/a6/Flour.png"
  "flower_pot|https://static.wikia.nocookie.net/arc-raiders/images/0/0a/Flower_Pot.png"
  "flywheel|https://static.wikia.nocookie.net/arc-raiders/images/9/9e/Flywheel.png"
  "fuel|https://static.wikia.nocookie.net/arc-raiders/images/5/50/Fuel.png"
  "fur_pelt|https://static.wikia.nocookie.net/arc-raiders/images/a/a5/Fur_Pelt.png"
  "fuse|https://static.wikia.nocookie.net/arc-raiders/images/f/f1/Fuse.png"
  "garlic|https://static.wikia.nocookie.net/arc-raiders/images/2/21/Garlic.png"
  "glass_bottle|https://static.wikia.nocookie.net/arc-raiders/images/c/c7/Glass_Bottle.png"
  "glass_jar|https://static.wikia.nocookie.net/arc-raiders/images/4/41/Glass_Jar.png"
  "globe|https://static.wikia.nocookie.net/arc-raiders/images/2/2d/Globe.png"
  "glue|https://static.wikia.nocookie.net/arc-raiders/images/0/03/Glue.png"
  "gold_coin|https://static.wikia.nocookie.net/arc-raiders/images/4/4a/Gold_Coin.png"
  "golden_bracelet|https://static.wikia.nocookie.net/arc-raiders/images/0/05/Golden_Bracelet.png"
  "golden_ring|https://static.wikia.nocookie.net/arc-raiders/images/4/48/Golden_Ring.png"
  "grapes|https://static.wikia.nocookie.net/arc-raiders/images/6/66/Grapes.png"
  "gunpowder|https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Gunpowder.png"
  "hair_brush|https://static.wikia.nocookie.net/arc-raiders/images/0/09/Hair_Brush.png"
  "hand_mirror|https://static.wikia.nocookie.net/arc-raiders/images/a/a7/Hand_Mirror.png"
  "hand_pump|https://static.wikia.nocookie.net/arc-raiders/images/4/46/Hand_Pump.png"
  "hardened_arc_plating|https://static.wikia.nocookie.net/arc-raiders/images/4/4e/Hardened_ARC_Plating.png"
  "heavy_gun_parts|https://static.wikia.nocookie.net/arc-raiders/images/f/f9/Heavy_Gun_Parts.png"
  "herbs|https://static.wikia.nocookie.net/arc-raiders/images/0/04/Herbs.png"
  "honey|https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Honey.png"
  "instant_noodles|https://static.wikia.nocookie.net/arc-raiders/images/9/94/Instant_Noodles.png"
  "kitchen_knife|https://static.wikia.nocookie.net/arc-raiders/images/3/35/Kitchen_Knife.png"
  "large_gear|https://static.wikia.nocookie.net/arc-raiders/images/e/e2/Large_Gear.png"
  "leather|https://static.wikia.nocookie.net/arc-raiders/images/4/42/Leather.png"
  "light_gun_parts|https://static.wikia.nocookie.net/arc-raiders/images/2/24/Light_Gun_Parts.png"
  "lightbulb|https://static.wikia.nocookie.net/arc-raiders/images/1/19/Lightbulb.png"
  "lighter|https://static.wikia.nocookie.net/arc-raiders/images/5/52/Lighter.png"
  "magnifying_glass|https://static.wikia.nocookie.net/arc-raiders/images/4/41/Magnifying_Glass.png"
  "matriarch_reactor|https://static.wikia.nocookie.net/arc-raiders/images/2/24/Matriarch_Reactor.png"
  "mechanical_components|https://static.wikia.nocookie.net/arc-raiders/images/9/94/Mechanical_Components.png"
  "medium_gun_parts|https://static.wikia.nocookie.net/arc-raiders/images/9/9a/Medium_Gun_Parts.png"
  "metal_brackets|https://static.wikia.nocookie.net/arc-raiders/images/6/62/Metal_Brackets.png"
  "metal_parts|https://static.wikia.nocookie.net/arc-raiders/images/8/89/Metal_Parts.png"
  "microscope|https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Microscope.png"
  "mini_centrifuge|https://static.wikia.nocookie.net/arc-raiders/images/9/9f/Mini_Centrifuge.png"
  "mod_components|https://static.wikia.nocookie.net/arc-raiders/images/c/c7/Mod_Components.png"
  "motor_oil|https://static.wikia.nocookie.net/arc-raiders/images/0/09/Motor_Oil.png"
  "mushroom|https://static.wikia.nocookie.net/arc-raiders/images/8/8c/Mushroom.png"
  "nails|https://static.wikia.nocookie.net/arc-raiders/images/f/f9/Nails.png"
  "olive|https://static.wikia.nocookie.net/arc-raiders/images/d/d1/Olive.png"
  "onion|https://static.wikia.nocookie.net/arc-raiders/images/6/62/Onion.png"
  "orange|https://static.wikia.nocookie.net/arc-raiders/images/5/52/Orange.png"
  "paint_can|https://static.wikia.nocookie.net/arc-raiders/images/5/5b/Paint_Can.png"
  "paper|https://static.wikia.nocookie.net/arc-raiders/images/3/37/Paper.png"
  "peach|https://static.wikia.nocookie.net/arc-raiders/images/f/f9/Peach.png"
  "pear|https://static.wikia.nocookie.net/arc-raiders/images/e/e3/Pear.png"
  "pillow|https://static.wikia.nocookie.net/arc-raiders/images/3/3e/Pillow.png"
  "plastic|https://static.wikia.nocookie.net/arc-raiders/images/7/78/Plastic.png"
  "pliers|https://static.wikia.nocookie.net/arc-raiders/images/f/f9/Pliers.png"
  "plum|https://static.wikia.nocookie.net/arc-raiders/images/4/40/Plum.png"
  "pomegranate|https://static.wikia.nocookie.net/arc-raiders/images/9/98/Pomegranate.png"
  "potato|https://static.wikia.nocookie.net/arc-raiders/images/e/e0/Potato.png"
  "prickly_pear|https://static.wikia.nocookie.net/arc-raiders/images/0/09/Prickly_Pear.png"
  "pristine_arc_circuitry|https://static.wikia.nocookie.net/arc-raiders/images/e/e7/Pristine_ARC_Circuitry.png"
  "pristine_arc_core|https://static.wikia.nocookie.net/arc-raiders/images/e/e0/Pristine_ARC_Core.png"
  "pristine_arc_optics|https://static.wikia.nocookie.net/arc-raiders/images/7/76/Pristine_ARC_Optics.png"
  "pristine_arc_plating|https://static.wikia.nocookie.net/arc-raiders/images/6/60/Pristine_ARC_Plating.png"
  "pristine_arc_powercell|https://static.wikia.nocookie.net/arc-raiders/images/d/d5/Pristine_ARC_Powercell.png"
  "propane_tank|https://static.wikia.nocookie.net/arc-raiders/images/2/23/Propane_Tank.png"
  "radio|https://static.wikia.nocookie.net/arc-raiders/images/6/6d/Radio.png"
  "rags|https://static.wikia.nocookie.net/arc-raiders/images/1/15/Rags.png"
  "rebar|https://static.wikia.nocookie.net/arc-raiders/images/d/d9/Rebar.png"
  "rechargeable_battery|https://static.wikia.nocookie.net/arc-raiders/images/7/71/Rechargeable_Battery.png"
  "resin|https://static.wikia.nocookie.net/arc-raiders/images/2/25/Resin.png"
  "ring|https://static.wikia.nocookie.net/arc-raiders/images/3/3a/Ring.png"
  "rope|https://static.wikia.nocookie.net/arc-raiders/images/f/f5/Rope.png"
  "rubber|https://static.wikia.nocookie.net/arc-raiders/images/2/21/Rubber.png"
  "ruined_parachute|https://static.wikia.nocookie.net/arc-raiders/images/5/5c/Ruined_Parachute.png"
  "ruined_riot_shield|https://static.wikia.nocookie.net/arc-raiders/images/c/cb/Ruined_Riot_Shield.png"
  "ruined_tactical_vest|https://static.wikia.nocookie.net/arc-raiders/images/c/c2/Ruined_Tactical_Vest.png"
  "rusted_bolts|https://static.wikia.nocookie.net/arc-raiders/images/b/bf/Rusted_Bolts.png"
  "rusted_gear|https://static.wikia.nocookie.net/arc-raiders/images/c/cf/Rusted_Gear.png"
  "rusted_shut_medical_kit|https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Rusted_Shut_Medical_Kit.png"
  "rusted_tools|https://static.wikia.nocookie.net/arc-raiders/images/3/30/Rusted_Tools.png"
  "rusty_arc_steel|https://static.wikia.nocookie.net/arc-raiders/images/e/e1/Rusty_ARC_Steel.png"
  "salt|https://static.wikia.nocookie.net/arc-raiders/images/5/59/Salt.png"
  "scalpel|https://static.wikia.nocookie.net/arc-raiders/images/5/55/Scalpel.png"
  "scissors|https://static.wikia.nocookie.net/arc-raiders/images/f/f2/Scissors.png"
  "scrap_metal|https://static.wikia.nocookie.net/arc-raiders/images/f/fd/Scrap_Metal.png"
  "screwdriver|https://static.wikia.nocookie.net/arc-raiders/images/9/96/Screwdriver.png"
  "sewing_kit|https://static.wikia.nocookie.net/arc-raiders/images/3/37/Sewing_Kit.png"
  "shrapnel|https://static.wikia.nocookie.net/arc-raiders/images/d/db/Shrapnel.png"
  "silver_necklace|https://static.wikia.nocookie.net/arc-raiders/images/2/2f/Silver_Necklace.png"
  "small_gear|https://static.wikia.nocookie.net/arc-raiders/images/6/65/Small_Gear.png"
  "soap|https://static.wikia.nocookie.net/arc-raiders/images/d/d6/Soap.png"
  "soldering_iron|https://static.wikia.nocookie.net/arc-raiders/images/2/2b/Soldering_Iron.png"
  "spatula|https://static.wikia.nocookie.net/arc-raiders/images/5/5a/Spatula.png"
  "spice|https://static.wikia.nocookie.net/arc-raiders/images/b/b9/Spice.png"
  "sponge|https://static.wikia.nocookie.net/arc-raiders/images/0/08/Sponge.png"
  "spoon|https://static.wikia.nocookie.net/arc-raiders/images/3/38/Spoon.png"
  "spring|https://static.wikia.nocookie.net/arc-raiders/images/5/5c/Spring.png"
  "stapler|https://static.wikia.nocookie.net/arc-raiders/images/4/42/Stapler.png"
  "steel_pipe|https://static.wikia.nocookie.net/arc-raiders/images/4/48/Steel_Pipe.png"
  "stethoscope|https://static.wikia.nocookie.net/arc-raiders/images/5/5c/Stethoscope.png"
  "strawberries|https://static.wikia.nocookie.net/arc-raiders/images/e/e7/Strawberries.png"
  "sugar|https://static.wikia.nocookie.net/arc-raiders/images/9/99/Sugar.png"
  "sunglasses|https://static.wikia.nocookie.net/arc-raiders/images/b/b9/Sunglasses.png"
  "surgical_mask|https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Surgical_Mask.png"
  "syringe|https://static.wikia.nocookie.net/arc-raiders/images/4/48/Syringe.png"
  "tennis_racket|https://static.wikia.nocookie.net/arc-raiders/images/8/8f/Tennis_Racket.png"
  "thermometer|https://static.wikia.nocookie.net/arc-raiders/images/2/26/Thermometer.png"
  "timer|https://static.wikia.nocookie.net/arc-raiders/images/3/3c/Timer.png"
  "tire|https://static.wikia.nocookie.net/arc-raiders/images/3/3a/Tire.png"
  "tomato|https://static.wikia.nocookie.net/arc-raiders/images/2/21/Tomato.png"
  "torch|https://static.wikia.nocookie.net/arc-raiders/images/4/43/Torch.png"
  "toy_car|https://static.wikia.nocookie.net/arc-raiders/images/f/f7/Toy_Car.png"
  "transistor|https://static.wikia.nocookie.net/arc-raiders/images/a/a2/Transistor.png"
  "umbrella|https://static.wikia.nocookie.net/arc-raiders/images/3/3a/Umbrella.png"
  "vacuum_tube|https://static.wikia.nocookie.net/arc-raiders/images/3/39/Vacuum_Tube.png"
  "walnut|https://static.wikia.nocookie.net/arc-raiders/images/5/5a/Walnut.png"
  "watermelon|https://static.wikia.nocookie.net/arc-raiders/images/6/63/Watermelon.png"
  "wheat|https://static.wikia.nocookie.net/arc-raiders/images/8/87/Wheat.png"
  "wire|https://static.wikia.nocookie.net/arc-raiders/images/1/1b/Wire.png"
  "wrench|https://static.wikia.nocookie.net/arc-raiders/images/b/bc/Wrench.png"
  "zip_ties|https://static.wikia.nocookie.net/arc-raiders/images/1/10/Zip_Ties.png"
)

echo "Starting download of ${#ITEMS[@]} images..."
echo "Output directory: $OUTPUT_DIR"

downloaded=0
skipped=0
failed=0

for item in "${ITEMS[@]}"; do
  IFS='|' read -r id url <<< "$item"
  filename="${id}.webp"
  filepath="$OUTPUT_DIR/$filename"

  # Download with curl, following redirects, with proper user agent
  # Request the original size image
  full_url="${url}/revision/latest?cb=20240101000000"

  http_code=$(curl -s -w "%{http_code}" -L \
    -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36" \
    -H "Accept: image/webp,image/png,image/*" \
    -o "$filepath" \
    "$full_url")

  # Check if download was successful and file is not a placeholder
  filesize=$(stat -f%z "$filepath" 2>/dev/null || echo "0")

  if [ "$http_code" = "200" ] && [ "$filesize" -gt 1000 ]; then
    echo "✓ Downloaded: $id ($filesize bytes)"
    ((downloaded++))
  elif [ "$filesize" -gt 0 ] && [ "$filesize" -le 1000 ]; then
    echo "⚠ Placeholder: $id (only $filesize bytes)"
    rm -f "$filepath"
    ((failed++))
  else
    echo "✗ Failed: $id (HTTP $http_code)"
    rm -f "$filepath"
    ((failed++))
  fi

  # Small delay to be nice to the server
  sleep 0.1
done

echo ""
echo "Download complete!"
echo "Downloaded: $downloaded"
echo "Failed/Placeholder: $failed"
